package vista;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.EventQueue;

import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.border.EmptyBorder;

import clases.Img;

import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

public class seleccionAutosBmw extends JFrame {
	Img img = new Img();
    public seleccionAutosBmw() {
    	addWindowListener(new WindowAdapter() {
    		
    		@Override
    		public void windowClosing(WindowEvent e) {
    			JOptionPane.showMessageDialog(null,"GRACIAS POR USAR NUESTRA APLICACION");
    		}
    	});
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        btnBm1 = new javax.swing.JButton();
        btnBm1.addMouseListener(new MouseAdapter() {
        	@Override
        	public void mouseEntered(MouseEvent e) {
        		btnBm1.setBackground(Color.cyan);
        	}
        	
        	@Override
        	public void mouseExited(MouseEvent e) {
        		btnBm1.setBackground(Color.WHITE);
        	}
        	
        });
        btnBm1.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		btnBm1.setBackground(Color.cyan);
        		lblAutoBmw.setIcon(new ImageIcon(img.ImgBmw(1, 1)));
        		lblPrecioBmw.setText("75046");
        	}
        });
        btnBm2 = new javax.swing.JButton();
        btnBm2.addMouseListener(new MouseAdapter() {
        	@Override
        	public void mouseEntered(MouseEvent e) {
        		btnBm2.setBackground(Color.cyan);
        	}
        	
        	@Override
        	public void mouseExited(MouseEvent e) {
        		btnBm2.setBackground(Color.WHITE);
        	}
        	@Override
        	public void mouseClicked(MouseEvent e) {
        		btnBm2.setBackground(Color.cyan);
        	}
        });
        btnBm4 = new javax.swing.JButton();
        btnBm4.addMouseListener(new MouseAdapter() {
        	@Override
        	public void mouseEntered(MouseEvent e) {
        		btnBm4.setBackground(Color.cyan);
        	}
        	
        	@Override
        	public void mouseExited(MouseEvent e) {
        		btnBm4.setBackground(Color.WHITE);
        	}
        	@Override
        	public void mouseClicked(MouseEvent e) {
        		btnBm4.setBackground(Color.cyan);
        	}
        });
        btnBm3 = new javax.swing.JButton();
        btnBm3.addMouseListener(new MouseAdapter() {
        	@Override
        	public void mouseEntered(MouseEvent e) {
        		btnBm3.setBackground(Color.cyan);
        	}
        	
        	@Override
        	public void mouseExited(MouseEvent e) {
        		btnBm3.setBackground(Color.WHITE);
        	}
        	@Override
        	public void mouseClicked(MouseEvent e) {
        		btnBm3.setBackground(Color.cyan);
        	}
        });
        btnBm3.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		lblAutoBmw.setIcon(new ImageIcon(img.ImgBmw(3, 1)));
        		lblPrecioBmw.setText("654100");
        		btnBm3.setBackground(Color.cyan);
        	}
        });
        btnBm6 = new javax.swing.JButton();
        btnBm6.addMouseListener(new MouseAdapter() {
        	@Override
        	public void mouseEntered(MouseEvent e) {
        		btnBm6.setBackground(Color.cyan);
        	}
        	
        	@Override
        	public void mouseExited(MouseEvent e) {
        		btnBm6.setBackground(Color.WHITE);
        	}
        	@Override
        	public void mouseClicked(MouseEvent e) {
        		btnBm6.setBackground(Color.cyan);
        	}
        });
        btnBm5 = new javax.swing.JButton();
        btnBm5.addMouseListener(new MouseAdapter() {
        	@Override
        	public void mouseEntered(MouseEvent e) {
        		btnBm5.setBackground(Color.cyan);
        	}
        	
        	@Override
        	public void mouseExited(MouseEvent e) {
        		btnBm5.setBackground(Color.WHITE);
        	}
        	@Override
        	public void mouseClicked(MouseEvent e) {
        		btnBm5.setBackground(Color.cyan);
        	}
        });
        btnBm5.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		lblAutoBmw.setIcon(new ImageIcon(img.ImgBmw(5, 1)));
        		lblPrecioBmw.setText("250131");
        		btnBm5.setBackground(Color.cyan);
        	}
        });
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblPrecioBmw = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lblAutoBmw = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        btnRealizarVentaBmw = new javax.swing.JButton();
        btnRealizarVentaBmw.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		dispose();
        		EventQueue.invokeLater(new Runnable() {
        			public void run() {
        				try {
        					VENTA frame = new VENTA();
        					frame.setVisible(true);
        				} catch (Exception e) {
        					e.printStackTrace();
        				}
        			}
        		});
        	}
        });
        btnRealizarVentaBmw.addMouseListener(new MouseAdapter() {
        	@Override
        	public void mouseEntered(MouseEvent e) {
        		 btnRealizarVentaBmw.setBackground(Color.cyan);
        	}
        	
        	@Override
        	public void mouseExited(MouseEvent e) {
        		 btnRealizarVentaBmw.setBackground(Color.WHITE);
        	}
        });
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem1.addMouseListener(new MouseAdapter() {
        	@Override
        	public void mousePressed(MouseEvent e) {
        		dispose();
        		new nimbus_linux();
        		java.awt.EventQueue.invokeLater(new Runnable() {
                    public void run() {
                        new inicioAutos().setVisible(true);
                    }
                });
        	}
        });
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1061, 706));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "BMW", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Emoji", 0, 14))); // NOI18N

        btnBm1.setBackground(new java.awt.Color(255, 255, 255));
        btnBm1.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        btnBm1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/extras/LogoVehiculo.png"))); // NOI18N
        btnBm1.setText("  BMW I4");

        btnBm2.setBackground(new java.awt.Color(255, 255, 255));
        btnBm2.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        btnBm2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/extras/LogoVehiculo.png"))); // NOI18N
        btnBm2.setText("  BMW I8");
        btnBm2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBm2ActionPerformed(evt);
            }
        });

        btnBm4.setBackground(new java.awt.Color(255, 255, 255));
        btnBm4.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        btnBm4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/extras/LogoVehiculo.png"))); // NOI18N
        btnBm4.setText("BMW SERIE 6");
        btnBm4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBm4ActionPerformed(evt);
            }
        });

        btnBm3.setBackground(new java.awt.Color(255, 255, 255));
        btnBm3.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        btnBm3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/extras/LogoVehiculo.png"))); // NOI18N
        btnBm3.setText("BMW SERIE 4");
        btnBm3.setToolTipText("");

        btnBm6.setBackground(new java.awt.Color(255, 255, 255));
        btnBm6.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        btnBm6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/extras/LogoVehiculo.png"))); // NOI18N
        btnBm6.setText("  BMW Z4");
        btnBm6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBm6ActionPerformed(evt);
            }
        });

        btnBm5.setBackground(new java.awt.Color(255, 255, 255));
        btnBm5.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        btnBm5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/extras/LogoVehiculo.png"))); // NOI18N
        btnBm5.setText("  BMW X5");
        btnBm5.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addComponent(jSeparator2)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnBm2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnBm1, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(btnBm4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnBm3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(btnBm5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                                        .addComponent(btnBm6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addGap(0, 12, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(btnBm1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBm2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBm3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBm4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBm5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBm6, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Precio", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/extras/LogoFacturacion.png"))); // NOI18N

        lblPrecioBmw.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblPrecioBmw.setText("...");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(lblPrecioBmw, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblPrecioBmw, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 12, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblAutoBmw.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bmw/1/1.jpeg"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAutoBmw, javax.swing.GroupLayout.PREFERRED_SIZE, 557, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAutoBmw, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/extras/LogoVenta.png"))); // NOI18N

        btnRealizarVentaBmw.setBackground(new java.awt.Color(255, 255, 255));
        btnRealizarVentaBmw.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        btnRealizarVentaBmw.setText("Realizar Venta");

        jDesktopPane1.setLayer(btnRealizarVentaBmw, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnRealizarVentaBmw)
                .addContainerGap())
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnRealizarVentaBmw)
                .addContainerGap())
        );

        jMenu1.setText("Men ");
        jMenuItem1.setText("Regresar");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Salir");
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Configuraci n");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jDesktopPane1)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBm2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBm2ActionPerformed
    	lblAutoBmw.setIcon(new ImageIcon(img.ImgBmw(2, 1)));
    	lblPrecioBmw.setText("85401");
    	btnBm2.setBackground(Color.cyan);
    }//GEN-LAST:event_btnBm2ActionPerformed

    private void btnBm4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBm4ActionPerformed
    	lblAutoBmw.setIcon(new ImageIcon(img.ImgBmw(4, 1)));
    	lblPrecioBmw.setText("465100");
    	btnBm4.setBackground(Color.cyan);
    }//GEN-LAST:event_btnBm4ActionPerformed

    private void btnBm6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBm6ActionPerformed
    	btnBm6.setBackground(Color.cyan);
    	lblAutoBmw.setIcon(new ImageIcon(img.ImgBmw(6, 1)));
    	lblPrecioBmw.setText("140012");
    }//GEN-LAST:event_btnBm6ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBm1;
    private javax.swing.JButton btnBm2;
    private javax.swing.JButton btnBm3;
    private javax.swing.JButton btnBm4;
    private javax.swing.JButton btnBm5;
    private javax.swing.JButton btnBm6;
    private javax.swing.JButton btnRealizarVentaBmw;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblAutoBmw;
    private javax.swing.JLabel lblPrecioBmw;
    // End of variables declaration//GEN-END:variables
}