package vista;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.EventQueue;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.border.EmptyBorder;

import clases.Img;
import clases.regulador;

import javax.swing.ImageIcon;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;

public class seleccionAutosLamb extends JFrame {
	regulador regu = new regulador();
	Img img = new Img();
    /**
     * Creates new form seleccionAutos
     */
    public seleccionAutosLamb() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    
    private void initComponents() {
    
        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        btnLamb1 = new javax.swing.JButton();        
        btnLamb1.addMouseListener(new MouseAdapter() {
        	@Override
        	public void mouseEntered(MouseEvent e) {
        		btnLamb1.setBackground(Color.red);
        		
        	}
        	
        	@Override
        	public void mouseExited(MouseEvent e) {
        		btnLamb1.setBackground(Color.WHITE);
        	}
        });
        btnLamb1.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		lblAutoLamb.setIcon(new ImageIcon(img.ImgLamb(1, 2)));
        		lblPrecioLamb.setText("100200");
        	}
        });
        btnLamb2 = new javax.swing.JButton();
        btnLamb2.addMouseListener(new MouseAdapter() {
        	@Override
        	public void mouseEntered(MouseEvent e) {
        		btnLamb2.setBackground(Color.red);
        		
        	}
        	
        	@Override
        	public void mouseExited(MouseEvent e) {
        		btnLamb2.setBackground(Color.WHITE);
        	}
        });
        btnLamb4 = new javax.swing.JButton();
        btnLamb4.addMouseListener(new MouseAdapter() {
        	@Override
        	public void mouseEntered(MouseEvent e) {
        		btnLamb4.setBackground(Color.red);
        		
        	}
        	
        	@Override
        	public void mouseExited(MouseEvent e) {
        		btnLamb4.setBackground(Color.WHITE);
        	}
        });
        btnLamb3 = new javax.swing.JButton();
        btnLamb3.addMouseListener(new MouseAdapter() {
        	@Override
        	public void mouseEntered(MouseEvent e) {
        		btnLamb3.setBackground(Color.red);
        		
        	}
        	
        	@Override
        	public void mouseExited(MouseEvent e) {
        		btnLamb3.setBackground(Color.WHITE);
        	}
        });
        btnLamb3.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		lblAutoLamb.setIcon(new ImageIcon(img.ImgLamb(3, 1)));
        		lblPrecioLamb.setText("98200");
        	}
        });
        btnLamb5 = new javax.swing.JButton();
        btnLamb5.addMouseListener(new MouseAdapter() {
        	@Override
        	public void mouseEntered(MouseEvent e) {
        		btnLamb5.setBackground(Color.red);
        		
        	}
        	
        	@Override
        	public void mouseExited(MouseEvent e) {
        		btnLamb5.setBackground(Color.WHITE);
        	}
        });
        btnLamb5.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		lblAutoLamb.setIcon(new ImageIcon(img.ImgLamb(5, 1)));
        		lblPrecioLamb.setText("450200");
        	}
        });
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblPrecioLamb = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lblAutoLamb = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        btnRealizarVentaLamb = new javax.swing.JButton();
        btnRealizarVentaLamb.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		dispose();
        		EventQueue.invokeLater(new Runnable() {
        			public void run() {
        				try {
        					VENTA frame = new VENTA();
        					frame.setVisible(true);
        				} catch (Exception e) {
        					e.printStackTrace();
        				}
        			}
        		});

        	}
        });
        btnRealizarVentaLamb.addMouseListener(new MouseAdapter() {
        	@Override
        	public void mouseEntered(MouseEvent e) {
        		btnRealizarVentaLamb.setBackground(Color.red);
        		
        	}
        	
        	@Override
        	public void mouseExited(MouseEvent e) {
        		btnRealizarVentaLamb.setBackground(Color.WHITE);
        	}
        });
        
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem1.addMouseListener(new MouseAdapter() {
        	@Override
        	public void mousePressed(MouseEvent e) {
        		dispose();
        		new nimbus_linux();
        		java.awt.EventQueue.invokeLater(new Runnable() {
                    public void run() {
                        new inicioAutos().setVisible(true);
                    }
                });
        	}
        });
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem2.addMouseListener(new MouseAdapter() {
        	@Override
        	public void mousePressed(MouseEvent e) {
        		System.exit(WIDTH);
        	}
        });
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "LAMBORGUINI", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Emoji", 0, 14))); // NOI18N

        btnLamb1.setBackground(new java.awt.Color(255, 255, 255));
        btnLamb1.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        btnLamb1.setIcon(new ImageIcon(seleccionAutosLamb.class.getResource("/extras/LogoVehiculo.png"))); // NOI18N
        btnLamb1.setText("AVENTADOR");

        btnLamb2.setBackground(new java.awt.Color(255, 255, 255));
        btnLamb2.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        btnLamb2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/extras/LogoVehiculo.png"))); // NOI18N
        btnLamb2.setText("GALLARDO");
        btnLamb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamb2ActionPerformed(evt);
            }
        });

        btnLamb4.setBackground(new java.awt.Color(255, 255, 255));
        btnLamb4.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        btnLamb4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/extras/LogoVehiculo.png"))); // NOI18N
        btnLamb4.setText("  SIAN");
        btnLamb4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamb4ActionPerformed(evt);
            }
        });

        btnLamb3.setBackground(new java.awt.Color(255, 255, 255));
        btnLamb3.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        btnLamb3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/extras/LogoVehiculo.png"))); // NOI18N
        btnLamb3.setText("HURACAN");
        btnLamb3.setToolTipText("");

        btnLamb5.setBackground(new java.awt.Color(255, 255, 255));
        btnLamb5.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        btnLamb5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/extras/LogoVehiculo.png"))); // NOI18N
        btnLamb5.setText("URUS");
        btnLamb5.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(btnLamb3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnLamb2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnLamb1, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnLamb4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnLamb5, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(4, 4, 4)))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addComponent(jSeparator2)
                            .addComponent(jSeparator3)
                            .addComponent(jSeparator4))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(btnLamb1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLamb2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLamb3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnLamb4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLamb5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Precio", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/extras/LogoFacturacion.png"))); // NOI18N

        lblPrecioLamb.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblPrecioLamb.setText("...");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(lblPrecioLamb, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblPrecioLamb, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 12, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblAutoLamb.setIcon(new ImageIcon(img.ImgLamb(1, 2)));
        
        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4Layout.setHorizontalGroup(
        	jPanel4Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(lblAutoLamb, GroupLayout.DEFAULT_SIZE, 546, Short.MAX_VALUE)
        			.addGap(21))
        );
        jPanel4Layout.setVerticalGroup(
        	jPanel4Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel4Layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(lblAutoLamb, GroupLayout.PREFERRED_SIZE, 375, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel4.setLayout(jPanel4Layout);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/extras/LogoVenta.png"))); // NOI18N

        btnRealizarVentaLamb.setBackground(new java.awt.Color(255, 255, 255));
        btnRealizarVentaLamb.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        btnRealizarVentaLamb.setText("Realizar Venta");

        jDesktopPane1.setLayer(btnRealizarVentaLamb, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnRealizarVentaLamb)
                .addContainerGap())
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnRealizarVentaLamb)
                .addContainerGap())
        );

        jMenu1.setText("Men�");

        jMenuItem1.setText("Regresar");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Salir");
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Configuraci�n");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addGap(18)
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addGroup(layout.createSequentialGroup()
        							.addGap(337)
        							.addComponent(jLabel4, GroupLayout.PREFERRED_SIZE, 63, GroupLayout.PREFERRED_SIZE)
        							.addGap(18)
        							.addComponent(jDesktopPane1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        						.addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
        				.addGroup(layout.createSequentialGroup()
        					.addPreferredGap(ComponentPlacement.UNRELATED)
        					.addComponent(jPanel4, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
        			.addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        			.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        				.addGroup(layout.createSequentialGroup()
        					.addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        					.addGap(18)
        					.addComponent(jPanel4, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        				.addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING, false)
        				.addComponent(jDesktopPane1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabel4, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        			.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLamb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamb2ActionPerformed
    	//lblAutoLamb.setIcon(new ImageIcon();
    	regu.Getregulador(lblAutoLamb, img.ImgLamb(2, 1));
    	lblPrecioLamb.setText("200100");
    }//GEN-LAST:event_btnLamb2ActionPerformed

    private void btnLamb4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamb4ActionPerformed
    	lblAutoLamb.setIcon(new ImageIcon(img.ImgLamb(4, 1)));
    	lblPrecioLamb.setText("300200");
    }//GEN-LAST:event_btnLamb4ActionPerformed

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLamb1;
    private javax.swing.JButton btnLamb2;
    private javax.swing.JButton btnLamb3;
    private javax.swing.JButton btnLamb4;
    private javax.swing.JButton btnLamb5;
    private javax.swing.JButton btnRealizarVentaLamb;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel lblAutoLamb;
    private javax.swing.JLabel lblPrecioLamb;
    // End of variables declaration//GEN-END:variables
}